using ExpressiveAnnotations.Attributes;
using ManahostManager.Domain.Entity;
using ManahostManager.Utils;
using System;
using System.ComponentModel.DataAnnotations;

namespace ManahostManager.Domain.DTOs
{
    // This table has multiple purpose
    // It will be used by managers for discount
    // It will be used by administrator for creating beta/trial keys
    // It will be used by administrator for discount on the price of Manahost

    public class KeyGeneratorDTO : IDTO
    {
        public int? Id { get; set; }

        // Expiration of the key
        [RequiredIf("Id == 0", ErrorMessage = GenericError.CANNOT_BE_NULL_OR_EMPTY)]
        public DateTime DateExp { get; set; }

        // See enumeration
        [RequiredIf("Id == 0", ErrorMessage = GenericError.CANNOT_BE_NULL_OR_EMPTY)]
        public EKeyType KeyType { get; set; }

        // See enumeration
        // Amount or percent
        [RequiredIf("Id == 0", ErrorMessage = GenericError.CANNOT_BE_NULL_OR_EMPTY)]
        public EValueType ValueType { get; set; }

        // Generated by the API, can't be modified by the Manager
        [MaxLength(256, ErrorMessage = GenericError.DOES_NOT_MEET_REQUIREMENTS)]
        public String Key { get; set; }

        // Discount
        public Decimal? Price { get; set; }

        // Reminder for the manager (example)
        [MaxLength(4000, ErrorMessage = GenericError.DOES_NOT_MEET_REQUIREMENTS)]
        public String Description { get; set; }

        // Optional Home
        public int? HomeId { get; set; }

        // Set by the API can't be modified by the manager
        public DateTime? DateModification { get; set; }

        int IDTO.HomeId
        {
            get
            {
                throw new NotImplementedException();
            }

            set
            {
                throw new NotImplementedException();
            }
        }
    }
}